import os
os.system("pip install google-cloud-speech")
os.system("pip install grpcio==1.44.0")
os.system("pip install grpcio-status==1.44.0")
os.system("pip install pyaudio")
os.system("sudo apt-get install portaudio19-dev python3-pyaudio")
os.system("sudo apt-get install libportaudio0 libportaudio2")
os.system("git clone https://github.com/URKnock/DIMIGO_RPI.git")
os.system("mv ~/DIMIGO_RPI/key.json ~/src/key.json")
os.system('export GOOGLE_APPLICATION_CREDENTIALS="/home/pi/src/key.json"')
